spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/joydeep-chowdhury/cloud-config-git-repo.git'
server:
  port: '${port:8888}'
