spring:
  application:
    name: property-access-service
  profiles:
    active: dev
    
  config:
    import: optional:configserver:http://localhost:8888
      
server:
  port: ${port:8080}
  
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'